### ISSUE TITLE
angular-bound-sensor doesn't work in IE 11

### ISSUE THREAD

**Issue by harikrishnan-u01** [aminpaks/bound-sensor#3]
Hi @aminpaks ,

The angular bound sensor breaks the entire application in IE due to script error:

![image](https://user-images.githubusercontent.com/10159959/29178409-78281fd8-7dbf-11e7-82b2-308bf296290f.png)

Even the examples mentioned in the documentation doesn't work in IE 11:
http://embed.plnkr.co/pDJqcOBO91RKR8qiZNUy/
http://embed.plnkr.co/kYRXPHT6rHc7dcLw0Pxo/

Thanks,
Hari

**Comment by aminpaks** [comment]
Hello,

I assume it's not BoundSensor itself, it's `CustomEvent` that it's causing this issue.
Have you tried to include `CustomEvents` polyfill in your app?
Basically IE 11 doesn't support `CustomEvents` and to get it to work you need to include [this package](https://www.npmjs.com/package/custom-event-polyfill) in your app vendor.

I will create another demo and will include it to demonstrate.

**Comment by harikrishnan-u01** [comment]
Hi @aminpaks ,

Thank you for the above tip.

We ended up adding the following polyfills to make this work in IE:

https://www.npmjs.com/package/custom-event-polyfill
https://www.npmjs.com/package/childnode-remove

IE doesn't support following method:
https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove
which was used in bound-sensor, so we also had to add childnode-remove.

And in the polyfill.ts we added:

`import 'custom-event-polyfill';`
`import * as childnode_remove from 'childnode-remove';`
`childnode_remove.polyfill();`

Thanks,
Hari

**Comment by aminpaks** [comment]
Glad it worked out.
I will add some notes regarding IE compatibility to read me.
