### ISSUE TITLE
ERROR TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by i2joseph** [aminpaks/bound-sensor#4]
Hi,
I got this error 
ERROR TypeError: Cannot read property 'addEventListener' of null

I am not sure what happens.

Can somebody help.

Thanks.

**Comment by aminpaks** [comment]
Hi,

Can you tell me more about the error?
What browser you're using?
When you're getting this error?

**Comment by aminpaks** [comment]
I close this because of lack of details.
Reopen it if needed.
