### ISSUE TITLE
Support for Angular version 5

### ISSUE THREAD

**Issue by harikrishnan-u01** [aminpaks/bound-sensor#7]
Hi @aminpaks ,

Can you kindly bump up the Angular version in package.json to Angular 5?
This is the only library which is preventing my project to migrate from Angular 4 to Angular 5.

Thanks,
Hari

**Comment by aminpaks** [comment]
Sure thing. Will do ASAP

**Comment by aminpaks** [comment]
Just published v1.1.0, should support angular v5. Tested with the example provided in the repo.

Good luck.
